SELECT p.*
FROM VEM_SER.PESSOA p RIGHT OUTER JOIN VEM_SER.CONTATO c
  ON VEM_SER.p.ID_PESSOA  = VEM_SER.c.ID_PESSOA
  
 
SELECT p.*
  FROM VEM_SER.PESSOA p 
  RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
  	ON VEM_SER.p.ID_PESSOA = VEM_SER.pxpe.ID_PESSOA


  	
  	-- trazendo a tabela da direita com todos os dados
-- RIGHT OUTER JOIN PESSOAS, PESSOA_X_PESSOA_ENDERECO, ENDERECO_PESSOA
SELECT p.* FROM VEM_SER.PESSOA p
    RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON
        p.ID_PESSOA  = pxpe.ID_PESSOA  
    RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA ep ON
        pxpe.ID_ENDERECO  = VEM_SER.ep.ID_ENDERECO 

        
-- RIGHT OUTER JOIN PESSOA, CONTATO, ENDERECO_PESSOA, PESSOA_X_ENDERECO_PESSOA

SELECT p.* FROM VEM_SER.PESSOA p
    RIGHT OUTER JOIN VEM_SER.CONTATO c ON
        p.ID_PESSOA  = c.ID_PESSOA 
    RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON
        c.ID_PESSOA  = pxpe.ID_PESSOA  
    RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA ep ON
        pxpe.ID_ENDERECO  = VEM_SER.ep.ID_ENDERECO 

        
-- OUTER FULL JOIN 

        
-- PESSOA CONTATO
SELECT p.*
FROM VEM_SER.PESSOA
FULL OUTER JOIN VEM_SER.CONTATO c
ON VEM_SER.p.ID_PESSOA  = VEM_SER.c.ID_PESSOA 




-- FULL OUTER JOIN PESSOAS, PESSOA_X_PESSOA_ENDERECO, ENDERECO_PESSOA
SELECT p.* FROM VEM_SER.PESSOA p
    FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON
        p.ID_PESSOA  = pxpe.ID_PESSOA  
    FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ep ON
        pxpe.ID_ENDERECO  = VEM_SER.ep.ID_ENDERECO 

        
        
--  FULL OUTER JOIN PESSOA, CONTATO, ENDERECO_PESSOA, PESSOA_X_ENDERECO_PESSOA
SELECT p.* FROM VEM_SER.PESSOA p
	FULL OUTER JOIN VEM_SER.CONTATO c ON 
		VEM_SER.p.ID_PESSOA  = VEM_SER.c.ID_PESSOA 
	FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe ON
		VEM_SER.c.ID_PESSOA = VEM_SER.pxpe.ID_PESSOA
	FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ep ON
		VEM_SER.pxpe.ID_ENDERECO = VEM_SER.ep.ID_ENDERECO

	
-- ENDERECOS QUE EXISTEM
SELECT VEM_SER.p.ID_PESSOA, VEM_SER.p.NOME		
	 FROM VEM_SER.PESSOA p
	 WHERE EXISTS 
	 (
	 -- ANALISO SE O ID DA PESSOA EXISTE NO ENDERECO ID PESSOA
	   SELECT VEM_SER.pxpe.ID_PESSOA  
	   FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	   WHERE VEM_SER.pxpe.ID_PESSOA = VEM_SER.p.ID_PESSOA
	 )

-- PEGAR INFORMACOES DAS DUAS TABELAS
	 
SELECT VEM_SER.P.ID_PESSOA, VEM_SER.P.NOME,VEM_SER.EP.ID_ENDERECO , VEM_SER.EP.LOGRADOURO 
  FROM VEM_SER.PESSOA P
  FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN VEM_SER.ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

  
SELECT * FROM PESSOA
	

	   