SELECT *
FROM VEM_SER.PESSOA RIGHT OUTER JOIN VEM_SER.CONTATO
  ON VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.CONTATO.ID_PESSOA
  
 
SELECT *
  FROM VEM_SER.PESSOA 
  RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO
  	ON VEM_SER.PESSOA.ID_PESSOA = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA


  	
-- RIGHT OUTER JOIN PESSOAS, PESSOA_X_PESSOA_ENDERECO, ENDERECO_PESSOA
SELECT * FROM VEM_SER.PESSOA
    RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON
        PESSOA.ID_PESSOA  = PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  
    RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA ON
        PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO 

        
-- RIGHT OUTER JOIN PESSOA, CONTATO, ENDERECO_PESSOA, PESSOA_X_ENDERECO_PESSOA

SELECT * FROM VEM_SER.PESSOA
    RIGHT OUTER JOIN VEM_SER.CONTATO ON
        PESSOA.ID_PESSOA  = CONTATO.ID_PESSOA 
    RIGHT OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON
        CONTATO.ID_PESSOA  = PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  
    RIGHT OUTER JOIN VEM_SER.ENDERECO_PESSOA ON
        PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO 

        
-- OUTER FULL JOIN 

        
-- PESSOA CONTATO
SELECT *
FROM VEM_SER.PESSOA
FULL OUTER JOIN VEM_SER.CONTATO
ON VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.CONTATO.ID_PESSOA 




-- FULL OUTER JOIN PESSOAS, PESSOA_X_PESSOA_ENDERECO, ENDERECO_PESSOA
SELECT * FROM VEM_SER.PESSOA
    FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON
        PESSOA.ID_PESSOA  = PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  
    FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ON
        PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO 

        
        
--  FULL OUTER JOIN PESSOA, CONTATO, ENDERECO_PESSOA, PESSOA_X_ENDERECO_PESSOA
SELECT * FROM VEM_SER.PESSOA
	FULL OUTER JOIN VEM_SER.CONTATO ON 
		VEM_SER.PESSOA.ID_PESSOA  = VEM_SER.CONTATO.ID_PESSOA 
	FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON
		VEM_SER.CONTATO.ID_PESSOA = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA
	FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ON
		VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO

	
-- ENDERECOS QUE EXISTEM
SELECT VEM_SER.PESSOA.ID_PESSOA, VEM_SER.PESSOA.NOME		
	 FROM VEM_SER.PESSOA
	 WHERE EXISTS 
	 (
	 -- ANALISO SE O ID DA PESSOA EXISTE NO ENDERECO ID PESSOA
	   SELECT VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  
	   FROM VEM_SER.PESSOA_X_PESSOA_ENDERECO
	   WHERE VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA = VEM_SER.PESSOA.ID_PESSOA
	 )

-- PEGAR INFORMACOES DAS DUAS TABELAS
	 
SELECT VEM_SER.ID_PESSOA, VEM_SER.NOME, VEM_SER.ENDERECO, VEM_SER.LOGRADOURO
FROM VEM_SER.PESSOA p
    FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO ON
        VEM_SER.PESSOA.ID_PESSOA = VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_PESSOA  
    FULL JOIN VEM_SER.ENDERECO_PESSOA ON
        VEM_SER.PESSOA_X_PESSOA_ENDERECO.ID_ENDERECO  = VEM_SER.ENDERECO_PESSOA.ID_ENDERECO 

	
SELECT VEM_SER.PESSOA.ID_PESSOA 
	 , VEM_SER.PESSOA.NOME 
	 , VEM_SER.ENDERECO.ID_ENDERECO 
	 , VEM_SER.ENDERECO.LOGRADOURO 
  FROM VEM_SER.PESSOA P
  FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN VEM_SER.ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

	 
	 
	 

	   